### ISSUE TITLE
Universal resolver fails to fetch mydata DID.

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/acapy-mydata-did-protocol#18]
When testing mydata DID with universal resolver it fails with following error:

[internalError] Driver cannot retrieve result for did:mydata:z6MkjNiGktLUrNrwMW6obMR85UsjYmLPFmcXc9qaiAGqPaJT: 400 Bad Request (invalid input!)

BR,
Jan

**Comment by JanLin** [comment]
Hi George,
I am not expert in uni-resolver but my assumption is that you need to register any updates of did:mydata with the resolver so when uni-resolver parses it can load the correct drivers.

**Comment by georgepadayatti** [comment]
Each did method in Uni resolver has a corresponding 'driver', we haven't updated the ours to support v2 did:mydata. The v2 did:mydata is not publically resolvable did, instead is similar to did:peer for connections but for data agreements. In the next update there will be public resolution capabilities.
